name: close-expired
description: Accepts a list of issues with dates in their titles, closing any that are past their date
inputs:
  path:
    required: true
    description: Path to the list of issues to check
runs:
  using: 'node12'
  main: 'dist/index.js'
